/**
 * Regression tests for finding #4: unauthenticated / wildcard-CORS /
 * arbitrary-file-read exposure on AuthZEN PDP + dashboard servers.
 *
 * These tests assert the NEW defaults:
 *   - Both servers bind to 127.0.0.1 by default.
 *   - Both servers require a bearer token when auth isn't explicitly disabled.
 *   - The dashboard has no /api/import route (arbitrary file disclosure removed).
 *   - Wildcard CORS is refused on non-loopback binds.
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { AuthZenServer } from '../src/authzen-server.js';
import { DashboardServer } from '../src/dashboard-server.js';
import { resolveSecurity } from '../src/server-security.js';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

function tmpDb(): string {
  return join(tmpdir(), `ovid-sec-test-${Date.now()}-${Math.random().toString(36).slice(2)}.db`);
}

describe('resolveSecurity', () => {
  it('defaults to loopback bind + auth required', () => {
    delete process.env.OVID_ME_BIND_HOST;
    delete process.env.OVID_ME_AUTH_TOKEN;
    delete process.env.OVID_ME_ALLOW_LOOPBACK_NO_AUTH;
    const s = resolveSecurity();
    expect(s.bindHost).toBe('127.0.0.1');
    expect(s.token).toBeTruthy();
    expect(s.tokenAutoGenerated).toBe(true);
  });

  it('honors OVID_ME_AUTH_TOKEN env var', () => {
    process.env.OVID_ME_AUTH_TOKEN = 'fixed-token-xyz';
    const s = resolveSecurity();
    expect(s.token).toBe('fixed-token-xyz');
    expect(s.tokenAutoGenerated).toBe(false);
    delete process.env.OVID_ME_AUTH_TOKEN;
  });

  it('permits disabling auth on loopback with env opt-in', () => {
    process.env.OVID_ME_ALLOW_LOOPBACK_NO_AUTH = '1';
    const s = resolveSecurity({ bindHost: '127.0.0.1' });
    expect(s.token).toBe(null);
    delete process.env.OVID_ME_ALLOW_LOOPBACK_NO_AUTH;
  });

  it('refuses wildcard CORS on non-loopback bind', () => {
    expect(() => resolveSecurity({
      bindHost: '0.0.0.0',
      corsAllowOrigins: ['*'],
    })).toThrow(/wildcard CORS/);
  });

  it('refuses wildcard CORS even on loopback without env opt-in', () => {
    delete process.env.OVID_ME_ALLOW_WILDCARD_CORS;
    expect(() => resolveSecurity({
      bindHost: '127.0.0.1',
      corsAllowOrigins: ['*'],
    })).toThrow(/wildcard CORS/);
  });

  it('allows specific-origin CORS allowlist', () => {
    const s = resolveSecurity({
      corsAllowOrigins: ['https://dashboard.example.com'],
    });
    expect(s.corsAllowOrigins).toEqual(['https://dashboard.example.com']);
  });
});

describe('AuthZenServer with auth enabled', () => {
  let server: AuthZenServer;
  let port: number;
  let token: string;

  beforeAll(async () => {
    server = new AuthZenServer({
      port: 0,
      security: { auth: { token: 'test-bearer-abc123' } },
      defaultPolicy: 'permit(principal, action == Ovid::Action::"read_file", resource);',
      ovidConfig: { mandateMode: 'enforce', engine: 'fallback' },
    });
    await server.start();
    port = (server as any).server.address().port;
    token = server.getAuthToken()!;
  });

  afterAll(async () => { await server.stop(); });

  it('rejects requests with no Authorization header', async () => {
    const res = await fetch(`http://127.0.0.1:${port}/`);
    expect(res.status).toBe(401);
  });

  it('rejects requests with wrong bearer token', async () => {
    const res = await fetch(`http://127.0.0.1:${port}/`, {
      headers: { Authorization: 'Bearer wrong-token' },
    });
    expect(res.status).toBe(401);
  });

  it('accepts requests with correct bearer token', async () => {
    const res = await fetch(`http://127.0.0.1:${port}/`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    expect(res.status).toBe(200);
  });

  it('gates /.well-known/authzen-configuration behind auth', async () => {
    // We don't want an unauthenticated endpoint advertising the PDP topology.
    const res = await fetch(`http://127.0.0.1:${port}/.well-known/authzen-configuration`);
    expect(res.status).toBe(401);
  });

  it('gates evaluation endpoint behind auth', async () => {
    const res = await fetch(`http://127.0.0.1:${port}/access/v1/evaluation`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        subject: { type: 'agent', id: 'a1' },
        action: { name: 'read_file' },
        resource: { type: 'file', id: '/x' },
      }),
    });
    expect(res.status).toBe(401);
  });

  it('accepts ?token= query string for GET convenience', async () => {
    const res = await fetch(`http://127.0.0.1:${port}/?token=${encodeURIComponent(token)}`);
    expect(res.status).toBe(200);
  });

  it('does not emit Access-Control-Allow-Origin by default', async () => {
    const res = await fetch(`http://127.0.0.1:${port}/`, {
      headers: { Authorization: `Bearer ${token}`, Origin: 'https://evil.example.com' },
    });
    expect(res.headers.get('Access-Control-Allow-Origin')).toBeNull();
  });
});

describe('DashboardServer with auth enabled', () => {
  let server: DashboardServer;
  let port: number;
  let token: string;
  const dbPath = tmpDb();

  beforeAll(async () => {
    server = new DashboardServer({
      port: 0,
      dbPath,
      security: { auth: { token: 'dash-bearer-xyz789' } },
    });
    await server.start();
    port = (server as any).server.address().port;
    token = server.getAuthToken()!;
  });

  afterAll(async () => {
    await server.stop();
    try { (await import('node:fs')).unlinkSync(dbPath); } catch {}
  });

  it('rejects index page without auth', async () => {
    const res = await fetch(`http://127.0.0.1:${port}/`);
    expect(res.status).toBe(401);
  });

  it('rejects API calls without auth', async () => {
    const res = await fetch(`http://127.0.0.1:${port}/api/overview`);
    expect(res.status).toBe(401);
  });

  it('accepts API calls with bearer token', async () => {
    const res = await fetch(`http://127.0.0.1:${port}/api/overview`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    expect(res.status).toBe(200);
  });

  it('confirms /api/import is gone (arbitrary file read mitigation)', async () => {
    const res = await fetch(`http://127.0.0.1:${port}/api/import`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
      body: JSON.stringify({ path: '/etc/passwd' }),
    });
    expect(res.status).toBe(404);
  });
});
