/**
 * Shared security helpers for OVID-ME's built-in HTTP servers
 * (AuthZEN PDP + forensics dashboard).
 *
 * Threat model:
 *   OVID-ME servers run on developer machines and sometimes on internal
 *   deployment hosts. Prior defaults exposed the dashboard + AuthZEN PDP
 *   on all interfaces with CORS: * and no authentication, meaning any
 *   process on a shared network -- or any browser on a workstation via
 *   a malicious webpage -- could drive the PDP or exfiltrate audit
 *   history.
 *
 * Defaults now:
 *   - Bind to 127.0.0.1 unless OVID_ME_BIND_HOST or config.host sets
 *     otherwise.
 *   - Require a bearer token unless:
 *       * the caller passes { auth: { disabled: true } } (for tests/
 *         explicit opt-out in trusted environments), or
 *       * the bind host is strictly loopback AND the environment
 *         variable OVID_ME_ALLOW_LOOPBACK_NO_AUTH=1 is set.
 *   - When a token is required but not provided, one is generated on
 *     startup, printed ONCE to stderr, and must be supplied via
 *     Authorization: Bearer <token> (or ?token= for GET convenience).
 *   - CORS: default is "same-origin-only" (no Access-Control-Allow-*
 *     headers emitted). If config.corsAllowOrigins is set, only those
 *     exact origins are allowed; '*' is rejected in production-like
 *     configurations (any non-loopback bind).
 *
 * This module does not bring in any HTTP framework; it operates on
 * raw Node http primitives to keep dependency surface tiny.
 */

import crypto from 'node:crypto';
import type { IncomingMessage, ServerResponse } from 'node:http';

export interface AuthConfig {
  /** Pre-shared bearer token. Clients must send Authorization: Bearer <token>. */
  token?: string;
  /**
   * Disable auth entirely. Only honored when bindHost is strictly loopback.
   * This flag exists for tests and for deployments that terminate auth
   * at an upstream proxy.
   */
  disabled?: boolean;
}

export interface SecurityConfig {
  /** Host to bind on. Default 127.0.0.1. */
  bindHost?: string;
  /** Bearer-token auth config. */
  auth?: AuthConfig;
  /**
   * Allowed CORS origins (exact match). Default: no CORS headers emitted.
   * Pass '*' to allow any origin (rejected unless bindHost is loopback
   * AND OVID_ME_ALLOW_WILDCARD_CORS=1 is set, to prevent accidental
   * production exposure).
   */
  corsAllowOrigins?: string[];
}

export interface ResolvedSecurity {
  bindHost: string;
  /** Effective bearer token, or null if auth is disabled. */
  token: string | null;
  /** true when this token was auto-generated at startup (should be logged). */
  tokenAutoGenerated: boolean;
  /** Allowed origins for CORS. */
  corsAllowOrigins: string[];
}

const LOOPBACK_HOSTS = new Set([
  '127.0.0.1', '::1', 'localhost',
]);

function isLoopback(host: string): boolean {
  return LOOPBACK_HOSTS.has(host);
}

/**
 * Resolve a SecurityConfig into concrete values, applying defaults and
 * safety checks. Throws if the config would produce an unsafe default
 * (e.g. wildcard CORS on a non-loopback bind without the explicit opt-in
 * env var).
 */
export function resolveSecurity(cfg?: SecurityConfig): ResolvedSecurity {
  const bindHost =
    cfg?.bindHost ??
    process.env.OVID_ME_BIND_HOST ??
    '127.0.0.1';

  const authDisabled =
    cfg?.auth?.disabled === true ||
    (isLoopback(bindHost) && process.env.OVID_ME_ALLOW_LOOPBACK_NO_AUTH === '1');

  let token: string | null = null;
  let tokenAutoGenerated = false;
  if (!authDisabled) {
    token =
      cfg?.auth?.token ??
      process.env.OVID_ME_AUTH_TOKEN ??
      null;
    if (!token) {
      token = crypto.randomBytes(24).toString('base64url');
      tokenAutoGenerated = true;
    }
  }

  // CORS policy
  const rawOrigins = cfg?.corsAllowOrigins ?? [];
  const corsAllowOrigins: string[] = [];
  for (const origin of rawOrigins) {
    if (origin === '*') {
      if (!isLoopback(bindHost) || process.env.OVID_ME_ALLOW_WILDCARD_CORS !== '1') {
        throw new Error(
          'refusing to enable wildcard CORS (\'*\'): only permitted on loopback binds with OVID_ME_ALLOW_WILDCARD_CORS=1 set explicitly',
        );
      }
    }
    corsAllowOrigins.push(origin);
  }

  return { bindHost, token, tokenAutoGenerated, corsAllowOrigins };
}

/**
 * Apply CORS headers for a request, if the origin is in the allow list.
 * Returns true if the response should short-circuit (OPTIONS preflight).
 */
export function applyCors(
  req: IncomingMessage,
  res: ServerResponse,
  security: ResolvedSecurity,
): boolean {
  const origin = req.headers.origin;
  if (origin && security.corsAllowOrigins.length > 0) {
    const allowed =
      security.corsAllowOrigins.includes('*') ||
      security.corsAllowOrigins.includes(origin);
    if (allowed) {
      res.setHeader('Access-Control-Allow-Origin', origin);
      res.setHeader('Vary', 'Origin');
      res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
      res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-Request-ID');
    }
  }
  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
    return true;
  }
  return false;
}

/**
 * Verify the request carries a valid bearer token. Returns true when
 * the request may proceed, false when the caller should reject.
 * Writes a 401 response on rejection.
 *
 * Accepts either:
 *   Authorization: Bearer <token>
 *   ?token=<token>          (query string; for convenience in dev)
 */
export function verifyAuth(
  req: IncomingMessage,
  res: ServerResponse,
  security: ResolvedSecurity,
): boolean {
  if (security.token === null) return true;

  const authHeader = req.headers.authorization;
  let presented: string | null = null;
  if (typeof authHeader === 'string' && authHeader.toLowerCase().startsWith('bearer ')) {
    presented = authHeader.slice(7).trim();
  } else {
    try {
      const url = new URL(req.url || '/', 'http://localhost');
      const qs = url.searchParams.get('token');
      if (qs) presented = qs;
    } catch {
      // ignore URL parse failures; they fall through to rejection
    }
  }

  if (!presented || !timingSafeEqual(presented, security.token)) {
    res.writeHead(401, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Unauthorized: missing or invalid bearer token' }));
    return false;
  }
  return true;
}

function timingSafeEqual(a: string, b: string): boolean {
  const ab = Buffer.from(a);
  const bb = Buffer.from(b);
  if (ab.length !== bb.length) return false;
  return crypto.timingSafeEqual(ab, bb);
}

/**
 * Print startup banner (stderr) that includes the effective auth token
 * ONLY when it was auto-generated. Pre-configured tokens are never
 * echoed back. Does nothing when auth is disabled.
 */
export function announceAuthToken(label: string, security: ResolvedSecurity): void {
  if (security.token === null) return;
  if (!security.tokenAutoGenerated) return;
  // eslint-disable-next-line no-console
  console.error(
    `[ovid-me:${label}] auth token (auto-generated): ${security.token}\n` +
    `[ovid-me:${label}] set OVID_ME_AUTH_TOKEN=<token> to pin across restarts.`,
  );
}
